package com.mrjaffesclass.apcs.todolist;

/**
 *
 * @author Roger Jaffe
 * @version 1.0
 */
public class AboutView extends javax.swing.JDialog {

  String version = "Version 1.0";
  
  /**
   * Creates new form AboutView
   * @param parent    Parent window - this is the MainView
   * @param modal     True because this should be a modal window
   */
  public AboutView(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    versionText.setText(version);
    this.setLocationRelativeTo(parent); // Set window location near the main window
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        useText = new javax.swing.JLabel();
        schoolText = new javax.swing.JLabel();
        versionText = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleText.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        titleText.setText("To Do List");

        useText.setText("For use in AP Computer Science");

        schoolText.setText("Patrick Henry High School");

        versionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionText.setText("Version 0.0");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("We recommend using a pencil and paper instead");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(titleText)
                    .addComponent(useText)
                    .addComponent(schoolText)
                    .addComponent(versionText)
                    .addComponent(okBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleText)
                .addGap(4, 4, 4)
                .addComponent(versionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schoolText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(okBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
    this.dispose();
  }//GEN-LAST:event_okBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel schoolText;
    private javax.swing.JLabel titleText;
    private javax.swing.JLabel useText;
    private javax.swing.JLabel versionText;
    // End of variables declaration//GEN-END:variables
}
